// Tamil Nadu 17th Legislative Assembly MLA Data (2026)
// Source: Election Commission of India

export const ASSEMBLY_METADATA = {
  electionYear: 2026,
  electionDate: "2026-04-23",
  chiefMinister: "C. Joseph Vijay",
  party: "TVK (Tamilaga Vettri Kazhagam)",
  totalSeats: 234,
  majorityMark: 118,
};

export const PARTY_COLORS = {
  TVK:    { bg: '#FF6B00', text: '#fff' },
  DMK:    { bg: '#CC0000', text: '#fff' },
  AIADMK: { bg: '#006400', text: '#fff' },
  INC:    { bg: '#1565C0', text: '#fff' },
  PMK:    { bg: '#FF8F00', text: '#fff' },
  VCK:    { bg: '#4A148C', text: '#fff' },
  CPI:    { bg: '#B71C1C', text: '#fff' },
  CPM:    { bg: '#D32F2F', text: '#fff' },
  IUML:   { bg: '#1B5E20', text: '#fff' },
  DMDK:   { bg: '#FF6F00', text: '#fff' },
  AMMK:   { bg: '#880E4F', text: '#fff' },
  BJP:    { bg: '#E65100', text: '#fff' },
};

// Revenue officers per district (District Collectors as of 2026)
export const DISTRICT_OFFICERS = {
  "Thiruvallur":      "Tmt. Alby John Varghese IAS – District Collector, Thiruvallur",
  "Chennai":          "Thiru. Rasheed Mubarak IAS – District Collector, Chennai",
  "Kancheepuram":     "Tmt. P. Jagadeesan IAS – District Collector, Kancheepuram",
  "Chengalpattu":     "Thiru. G. Prakash IAS – District Collector, Chengalpattu",
  "Ranipet":          "Tmt. M. Periasamy IAS – District Collector, Ranipet",
  "Vellore":          "Thiru. V.R. Subbulakshmi IAS – District Collector, Vellore",
  "Tirupathur":       "Tmt. B. Chandra Mohan IAS – District Collector, Tirupathur",
  "Krishnagiri":      "Thiru. G. Lakshmi Priya IAS – District Collector, Krishnagiri",
  "Dharmapuri":       "Tmt. G. Elangovan IAS – District Collector, Dharmapuri",
  "Tiruvannamalai":   "Thiru. R. Brindha Devi IAS – District Collector, Tiruvannamalai",
  "Viluppuram":       "Tmt. D. Mohan IAS – District Collector, Viluppuram",
  "Kallakurichi":     "Thiru. M. Dhilip Kumar IAS – District Collector, Kallakurichi",
  "Salem":            "Tmt. S. Karmegham IAS – District Collector, Salem",
  "Namakkal":         "Thiru. S.Uma Maheswar IAS – District Collector, Namakkal",
  "Erode":            "Tmt. Raja Gopal Sunkara IAS – District Collector, Erode",
  "Tiruppur":         "Thiru. T. Christuraj IAS – District Collector, Tiruppur",
  "The Nilgiris":     "Tmt. Innocent Divya IAS – District Collector, The Nilgiris",
  "Coimbatore":       "Thiru. Kranthi Kumar Pati IAS – District Collector, Coimbatore",
  "Dindigul":         "Tmt. M.N. Poongodi IAS – District Collector, Dindigul",
  "Karur":            "Thiru. T. Anbalagan IAS – District Collector, Karur",
  "Tiruchirappalli":  "Tmt. M. Pradeep Kumar IAS – District Collector, Tiruchirappalli",
  "Perambalur":       "Thiru. S. Sivasubramanian IAS – District Collector, Perambalur",
  "Ariyalur":         "Tmt. G. Lakshmi IAS – District Collector, Ariyalur",
  "Cuddalore":        "Thiru. C. Kathiravan IAS – District Collector, Cuddalore",
  "Mayiladuthurai":   "Tmt. A.P. Mahesh Kumar IAS – District Collector, Mayiladuthurai",
  "Nagapattinam":     "Thiru. A. Shyam Sundar IAS – District Collector, Nagapattinam",
  "Thiruvarur":       "Tmt. P. Kavitha IAS – District Collector, Thiruvarur",
  "Thanjavur":        "Thiru. D. Baskara Pandian IAS – District Collector, Thanjavur",
  "Pudukkottai":      "Tmt. T.S. Thameem Ansari IAS – District Collector, Pudukkottai",
  "Sivaganga":        "Thiru. P.B. Janarthanan IAS – District Collector, Sivaganga",
  "Madurai":          "Tmt. M.S. Sangeetha IAS – District Collector, Madurai",
  "Theni":            "Thiru. P. Madhusudhan Reddy IAS – District Collector, Theni",
  "Virudhunagar":     "Tmt. Meghanath Reddy IAS – District Collector, Virudhunagar",
  "Ramanathapuram":   "Thiru. S. Aneesh Sekhar IAS – District Collector, Ramanathapuram",
  "Thoothukudi":      "Tmt. G. Lakshmipathy IAS – District Collector, Thoothukudi",
  "Tenkasi":          "Thiru. V. Vishnu IAS – District Collector, Tenkasi",
  "Tirunelveli":      "Tmt. G. Mythili IAS – District Collector, Tirunelveli",
  "Kanniyakumari":    "Thiru. P. Balachandran IAS – District Collector, Kanniyakumari",
};

export const MLA_DATA = [
  {"ac_no":1,"constituency":"Gummidipoondi","district":"Thiruvallur","mla":"S. Vijayakumar","party":"TVK"},
  {"ac_no":2,"constituency":"Ponneri (SC)","district":"Thiruvallur","mla":"Dr. Ravi M.S","party":"TVK"},
  {"ac_no":3,"constituency":"Tiruttani","district":"Thiruvallur","mla":"G. Hari","party":"AIADMK"},
  {"ac_no":4,"constituency":"Thiruvallur","district":"Thiruvallur","mla":"Dr. T. Arunkumar","party":"TVK"},
  {"ac_no":5,"constituency":"Poonamallee (SC)","district":"Thiruvallur","mla":"Prakasam R.","party":"TVK"},
  {"ac_no":6,"constituency":"Avadi","district":"Thiruvallur","mla":"R. Ramesh Kumar","party":"TVK"},
  {"ac_no":7,"constituency":"Maduravoyal","district":"Thiruvallur","mla":"Rhevanth Charan","party":"TVK"},
  {"ac_no":8,"constituency":"Ambattur","district":"Thiruvallur","mla":"Balamurugan G.","party":"TVK"},
  {"ac_no":9,"constituency":"Madavaram","district":"Thiruvallur","mla":"M.L. Vijayprabhu","party":"TVK"},
  {"ac_no":10,"constituency":"Thiruvottiyur","district":"Thiruvallur","mla":"Senthil Kumar N.","party":"TVK"},
  {"ac_no":11,"constituency":"Dr. Radhakrishnan Nagar","district":"Chennai","mla":"N. Marie Wilson","party":"TVK"},
  {"ac_no":12,"constituency":"Perambur","district":"Chennai","mla":"C. Joseph Vijay","party":"TVK"},
  {"ac_no":13,"constituency":"Kolathur","district":"Chennai","mla":"V. S. Babu","party":"TVK"},
  {"ac_no":14,"constituency":"Villivakkam","district":"Chennai","mla":"Aadhav Arjuna","party":"TVK"},
  {"ac_no":15,"constituency":"Thiru-Vi-Ka-Nagar (SC)","district":"Chennai","mla":"M. R. Pallavi","party":"TVK"},
  {"ac_no":16,"constituency":"Egmore (SC)","district":"Chennai","mla":"Rajmohan","party":"TVK"},
  {"ac_no":17,"constituency":"Royapuram","district":"Chennai","mla":"K.V. Vijay Damu","party":"TVK"},
  {"ac_no":18,"constituency":"Harbour","district":"Chennai","mla":"P. K. Sekarbabu","party":"DMK"},
  {"ac_no":19,"constituency":"Chepauk-Thiruvallikeni","district":"Chennai","mla":"Udhayanidhi Stalin","party":"DMK"},
  {"ac_no":20,"constituency":"Thousand Lights","district":"Chennai","mla":"Prabhakar J.C.D","party":"TVK"},
  {"ac_no":21,"constituency":"Anna Nagar","district":"Chennai","mla":"V.K. Ramkumar","party":"TVK"},
  {"ac_no":22,"constituency":"Virugampakkam","district":"Chennai","mla":"Sabarinathan R.","party":"TVK"},
  {"ac_no":23,"constituency":"Saidapet","district":"Chennai","mla":"Arul Prakasam M.","party":"TVK"},
  {"ac_no":24,"constituency":"Thiyagarayanagar","district":"Chennai","mla":"Anand N.","party":"TVK"},
  {"ac_no":25,"constituency":"Mylapore","district":"Chennai","mla":"Venkataramanan P.","party":"TVK"},
  {"ac_no":26,"constituency":"Velachery","district":"Chennai","mla":"Kumar R.","party":"TVK"},
  {"ac_no":27,"constituency":"Shozhinganallur","district":"Chengalpattu","mla":"ECR P. Saravanan","party":"TVK"},
  {"ac_no":28,"constituency":"Alandur","district":"Chengalpattu","mla":"M. Harish","party":"TVK"},
  {"ac_no":29,"constituency":"Sriperumbudur (SC)","district":"Kancheepuram","mla":"Thennarasu K.","party":"TVK"},
  {"ac_no":30,"constituency":"Pallavaram","district":"Chengalpattu","mla":"J. Kamatchi","party":"TVK"},
  {"ac_no":31,"constituency":"Tambaram","district":"Chengalpattu","mla":"D. Sarathkumar","party":"TVK"},
  {"ac_no":32,"constituency":"Chengalpattu","district":"Chengalpattu","mla":"S. Thiyagarajan","party":"TVK"},
  {"ac_no":33,"constituency":"Thiruporur","district":"Chengalpattu","mla":"B. Vijayaraj","party":"TVK"},
  {"ac_no":34,"constituency":"Cheyyur (SC)","district":"Chengalpattu","mla":"Rajasekar E.","party":"AIADMK"},
  {"ac_no":35,"constituency":"Madurantakam (SC)","district":"Chengalpattu","mla":"Maragatham Kumaravel K.","party":"AIADMK"},
  {"ac_no":36,"constituency":"Uthiramerur","district":"Kancheepuram","mla":"Munirathinam J.","party":"TVK"},
  {"ac_no":37,"constituency":"Kancheepuram","district":"Kancheepuram","mla":"R.V. Ranjithkumar","party":"TVK"},
  {"ac_no":38,"constituency":"Arakkonam (SC)","district":"Ranipet","mla":"V. Gandhiraj","party":"TVK"},
  {"ac_no":39,"constituency":"Sholinghur","district":"Ranipet","mla":"G. Kapil","party":"TVK"},
  {"ac_no":40,"constituency":"Katpadi","district":"Vellore","mla":"Dr. M. Sudhakar","party":"TVK"},
  {"ac_no":41,"constituency":"Ranipet","district":"Ranipet","mla":"Thahira","party":"TVK"},
  {"ac_no":42,"constituency":"Arcot","district":"Ranipet","mla":"S.M. Sukumar","party":"AIADMK"},
  {"ac_no":43,"constituency":"Vellore","district":"Vellore","mla":"M.M. Vinoth Kannan","party":"TVK"},
  {"ac_no":44,"constituency":"Anaikattu","district":"Vellore","mla":"D. Velazhagan","party":"AIADMK"},
  {"ac_no":45,"constituency":"Kilvaithinankuppam (SC)","district":"Vellore","mla":"Thenral Kumar E.","party":"TVK"},
  {"ac_no":46,"constituency":"Gudiyattam (SC)","district":"Vellore","mla":"K. Sindu","party":"TVK"},
  {"ac_no":47,"constituency":"Vaniyambadi","district":"Tirupathur","mla":"Syed Farooq Basha SSB","party":"IUML"},
  {"ac_no":48,"constituency":"Ambur","district":"Tirupathur","mla":"Vilwanathan A.C.","party":"DMK"},
  {"ac_no":49,"constituency":"Jolarpet","district":"Tirupathur","mla":"Veeramani K.C.","party":"AIADMK"},
  {"ac_no":50,"constituency":"Tirupattur","district":"Tirupathur","mla":"Dr. Thirupathi N.","party":"TVK"},
  {"ac_no":51,"constituency":"Uthangarai (SC)","district":"Krishnagiri","mla":"N. Elaiyaraja","party":"TVK"},
  {"ac_no":52,"constituency":"Bargur","district":"Krishnagiri","mla":"E.C. Govindarasan","party":"AIADMK"},
  {"ac_no":53,"constituency":"Krishnagiri","district":"Krishnagiri","mla":"Mukundhan P.","party":"TVK"},
  {"ac_no":54,"constituency":"Veppanahalli","district":"Krishnagiri","mla":"Srinivasan P.S.","party":"DMK"},
  {"ac_no":55,"constituency":"Hosur","district":"Krishnagiri","mla":"Balakrishnareddy P.","party":"AIADMK"},
  {"ac_no":56,"constituency":"Thalli","district":"Krishnagiri","mla":"Ramachandran T.","party":"CPI"},
  {"ac_no":57,"constituency":"Palacodu","district":"Dharmapuri","mla":"Anbalagan K.P.","party":"AIADMK"},
  {"ac_no":58,"constituency":"Pennagaram","district":"Dharmapuri","mla":"Gajendran S.","party":"TVK"},
  {"ac_no":59,"constituency":"Dharmapuri","district":"Dharmapuri","mla":"Sowmiya Anbumani","party":"PMK"},
  {"ac_no":60,"constituency":"Pappireddipatti","district":"Dharmapuri","mla":"Maragatham Vetrivel","party":"AIADMK"},
  {"ac_no":61,"constituency":"Harur (SC)","district":"Dharmapuri","mla":"Sampathkumar V.","party":"AIADMK"},
  {"ac_no":62,"constituency":"Chengam (SC)","district":"Tiruvannamalai","mla":"S. Velu","party":"AIADMK"},
  {"ac_no":63,"constituency":"Tiruvannamalai","district":"Tiruvannamalai","mla":"Velu E.V.","party":"DMK"},
  {"ac_no":64,"constituency":"Kilpennathur","district":"Tiruvannamalai","mla":"Ramachandran S.","party":"AIADMK"},
  {"ac_no":65,"constituency":"Kalasapakkam","district":"Tiruvannamalai","mla":"Agri Krishnamurthy S.S.","party":"AIADMK"},
  {"ac_no":66,"constituency":"Polur","district":"Tiruvannamalai","mla":"Abishek R.","party":"TVK"},
  {"ac_no":67,"constituency":"Arani","district":"Tiruvannamalai","mla":"Jayasudha L.","party":"AIADMK"},
  {"ac_no":68,"constituency":"Cheyyar","district":"Tiruvannamalai","mla":"Mukkur N. Subramanian","party":"AIADMK"},
  {"ac_no":69,"constituency":"Vandavasi (SC)","district":"Tiruvannamalai","mla":"Ambethkumar S.","party":"DMK"},
  {"ac_no":70,"constituency":"Gingee","district":"Viluppuram","mla":"Ganeshkumar A.","party":"PMK"},
  {"ac_no":71,"constituency":"Mailam","district":"Viluppuram","mla":"Shanmugam C. Ve.","party":"AIADMK"},
  {"ac_no":72,"constituency":"Tindivanam (SC)","district":"Viluppuram","mla":"Vanni Arasu","party":"VCK"},
  {"ac_no":73,"constituency":"Vanur (SC)","district":"Viluppuram","mla":"Gowtham D.","party":"DMK"},
  {"ac_no":74,"constituency":"Viluppuram","district":"Viluppuram","mla":"Lakshmanan R.","party":"DMK"},
  {"ac_no":75,"constituency":"Vikravandi","district":"Viluppuram","mla":"Sivakumar C.","party":"PMK"},
  {"ac_no":76,"constituency":"Tirukkoyilur","district":"Viluppuram","mla":"Palanisamy S.","party":"AIADMK"},
  {"ac_no":77,"constituency":"Ulundurpettai","district":"Kallakurichi","mla":"Vasanthavel G.R.","party":"DMK"},
  {"ac_no":78,"constituency":"Rishivandiyam","district":"Kallakurichi","mla":"Karthikeyan K.","party":"DMK"},
  {"ac_no":79,"constituency":"Sankarapuram","district":"Kallakurichi","mla":"Rakesh R.","party":"AIADMK"},
  {"ac_no":80,"constituency":"Kallakurichi (SC)","district":"Kallakurichi","mla":"Arul Vignesh C.","party":"TVK"},
  {"ac_no":81,"constituency":"Gangavalli (SC)","district":"Salem","mla":"Nallathambi A.","party":"AIADMK"},
  {"ac_no":82,"constituency":"Attur (SC)","district":"Salem","mla":"Jayasankaran A.P.","party":"AIADMK"},
  {"ac_no":83,"constituency":"Yercaud (ST)","district":"Salem","mla":"Usharani P.","party":"AIADMK"},
  {"ac_no":84,"constituency":"Omalur","district":"Salem","mla":"Mani R.","party":"AIADMK"},
  {"ac_no":85,"constituency":"Mettur","district":"Salem","mla":"Venkatachalam G.","party":"AIADMK"},
  {"ac_no":86,"constituency":"Edappadi","district":"Salem","mla":"Edappadi K. Palaniswami","party":"AIADMK"},
  {"ac_no":87,"constituency":"Sankari","district":"Salem","mla":"Vetrivel S.","party":"AIADMK"},
  {"ac_no":88,"constituency":"Salem (West)","district":"Salem","mla":"Lakshmanan S.","party":"TVK"},
  {"ac_no":89,"constituency":"Salem (North)","district":"Salem","mla":"Sivakumar K.","party":"TVK"},
  {"ac_no":90,"constituency":"Salem (South)","district":"Salem","mla":"Vijay Tamilan Parthiban A.","party":"TVK"},
  {"ac_no":91,"constituency":"Veerapandi","district":"Salem","mla":"Palanivel M.S.","party":"TVK"},
  {"ac_no":92,"constituency":"Rasipuram (SC)","district":"Namakkal","mla":"Logesh Tamilselvan D.","party":"TVK"},
  {"ac_no":93,"constituency":"Senthamangalam (ST)","district":"Namakkal","mla":"P. Chandrasekar","party":"TVK"},
  {"ac_no":94,"constituency":"Namakkal","district":"Namakkal","mla":"Dilip C.S.","party":"TVK"},
  {"ac_no":95,"constituency":"Paramathi-Velur","district":"Namakkal","mla":"Sekar S.","party":"AIADMK"},
  {"ac_no":96,"constituency":"Tiruchengodu","district":"Namakkal","mla":"Arunraj K.G.","party":"TVK"},
  {"ac_no":97,"constituency":"Kumarapalayam","district":"Namakkal","mla":"C. Vijayalakshmi","party":"TVK"},
  {"ac_no":98,"constituency":"Erode (East)","district":"Erode","mla":"M. Vijay Balaji","party":"TVK"},
  {"ac_no":99,"constituency":"Erode (West)","district":"Erode","mla":"Ananth Moghan K.K.","party":"TVK"},
  {"ac_no":100,"constituency":"Modakkurichi","district":"Erode","mla":"D. Shanmugan","party":"TVK"},
  {"ac_no":101,"constituency":"Dharapuram (SC)","district":"Tiruppur","mla":"Sathyabama P.","party":"AIADMK"},
  {"ac_no":102,"constituency":"Kangayam","district":"Tiruppur","mla":"NSN Nataraj","party":"AIADMK"},
  {"ac_no":103,"constituency":"Perundurai","district":"Erode","mla":"Jayakumar S.","party":"AIADMK"},
  {"ac_no":104,"constituency":"Bhavani","district":"Erode","mla":"Karuppanan K.C.","party":"AIADMK"},
  {"ac_no":105,"constituency":"Anthiyur","district":"Erode","mla":"Haribaskar P.","party":"AIADMK"},
  {"ac_no":106,"constituency":"Gobichettipalayam","district":"Erode","mla":"S. Sengottaiyan K.A.","party":"TVK"},
  {"ac_no":107,"constituency":"Bhavanisagar (SC)","district":"Erode","mla":"V.P. Tamilselvi","party":"TVK"},
  {"ac_no":108,"constituency":"Udhagamandalam","district":"The Nilgiris","mla":"Bhojarajan M.","party":"BJP"},
  {"ac_no":109,"constituency":"Gudalur (SC)","district":"The Nilgiris","mla":"Dhravidamani M.","party":"DMK"},
  {"ac_no":110,"constituency":"Coonoor","district":"The Nilgiris","mla":"M. Raju","party":"DMK"},
  {"ac_no":111,"constituency":"Mettuppalayam","district":"Coimbatore","mla":"Sunilanand","party":"TVK"},
  {"ac_no":112,"constituency":"Avanashi (SC)","district":"Tiruppur","mla":"Kamali S.","party":"TVK"},
  {"ac_no":113,"constituency":"Tiruppur (North)","district":"Tiruppur","mla":"V. Sathyabama","party":"TVK"},
  {"ac_no":114,"constituency":"Tiruppur (South)","district":"Tiruppur","mla":"Balamurugan S.","party":"TVK"},
  {"ac_no":115,"constituency":"Palladam","district":"Tiruppur","mla":"K. Ramkumar","party":"TVK"},
  {"ac_no":116,"constituency":"Sulur","district":"Coimbatore","mla":"N.M. Sukumar","party":"TVK"},
  {"ac_no":117,"constituency":"Kavundampalayam","district":"Coimbatore","mla":"Kanimozhi Santhosh","party":"TVK"},
  {"ac_no":118,"constituency":"Coimbatore (North)","district":"Coimbatore","mla":"V. Sampathkumar","party":"TVK"},
  {"ac_no":119,"constituency":"Thondamuthur","district":"Coimbatore","mla":"S.P. Velumani","party":"AIADMK"},
  {"ac_no":120,"constituency":"Coimbatore (South)","district":"Coimbatore","mla":"V. Senthilbalaji","party":"DMK"},
  {"ac_no":121,"constituency":"Singanallur","district":"Coimbatore","mla":"K.S. Sri Giri Prasath","party":"TVK"},
  {"ac_no":122,"constituency":"Kinathukadavu","district":"Coimbatore","mla":"Vignesh K.","party":"TVK"},
  {"ac_no":123,"constituency":"Pollachi","district":"Coimbatore","mla":"K. Nithyanandhan","party":"DMK"},
  {"ac_no":124,"constituency":"Valparai (SC)","district":"Coimbatore","mla":"Kutty (alias) Sudhakar A.","party":"DMK"},
  {"ac_no":125,"constituency":"Udumalaipettai","district":"Tiruppur","mla":"Jayakumar M.","party":"DMK"},
  {"ac_no":126,"constituency":"Madathukulam","district":"Tiruppur","mla":"R. Jayaramakrishnan","party":"DMK"},
  {"ac_no":127,"constituency":"Palani","district":"Dindigul","mla":"Ravimanoharan K.","party":"AIADMK"},
  {"ac_no":128,"constituency":"Oddanchatram","district":"Dindigul","mla":"Sakkarapani R.","party":"DMK"},
  {"ac_no":129,"constituency":"Athoor","district":"Dindigul","mla":"I. Periasamy","party":"DMK"},
  {"ac_no":130,"constituency":"Nilakkottai (SC)","district":"Dindigul","mla":"Ayyanar R.","party":"TVK"},
  {"ac_no":131,"constituency":"Natham","district":"Dindigul","mla":"Natham Viswanathan R.","party":"AIADMK"},
  {"ac_no":132,"constituency":"Dindigul","district":"Dindigul","mla":"Senthilkumar I.P.","party":"DMK"},
  {"ac_no":133,"constituency":"Vedasandur","district":"Dindigul","mla":"Saminathan T.","party":"DMK"},
  {"ac_no":134,"constituency":"Aravakurichi","district":"Karur","mla":"Elango R.","party":"DMK"},
  {"ac_no":135,"constituency":"Karur","district":"Karur","mla":"M.R. Vijayabhaskar","party":"AIADMK"},
  {"ac_no":136,"constituency":"Krishnarayapuram (SC)","district":"Karur","mla":"Sathya M.","party":"TVK"},
  {"ac_no":137,"constituency":"Kulithalai","district":"Karur","mla":"Suriyanur A. Chandran","party":"DMK"},
  {"ac_no":138,"constituency":"Manapparai","district":"Tiruchirappalli","mla":"R. Kathiravan","party":"TVK"},
  {"ac_no":139,"constituency":"Srirangam","district":"Tiruchirappalli","mla":"Ramesh","party":"TVK"},
  {"ac_no":140,"constituency":"Tiruchirappalli (West)","district":"Tiruchirappalli","mla":"K.N. Nehru","party":"DMK"},
  {"ac_no":141,"constituency":"Tiruchirappalli (East)","district":"Tiruchirappalli","mla":"C. Joseph Vijay","party":"TVK"},
  {"ac_no":142,"constituency":"Thiruverumbur","district":"Tiruchirappalli","mla":"Vijayakumar (A) Navalpattu S. Viji","party":"TVK"},
  {"ac_no":143,"constituency":"Lalgudi","district":"Tiruchirappalli","mla":"Leemarose Martin","party":"AIADMK"},
  {"ac_no":144,"constituency":"Manachanallur","district":"Tiruchirappalli","mla":"Kathiravan S.","party":"DMK"},
  {"ac_no":145,"constituency":"Musiri","district":"Tiruchirappalli","mla":"M. Vignesh","party":"TVK"},
  {"ac_no":146,"constituency":"Thuraiyur (SC)","district":"Tiruchirappalli","mla":"Ravisankar M.","party":"TVK"},
  {"ac_no":147,"constituency":"Perambalur (SC)","district":"Perambalur","mla":"Sivakumar K.","party":"TVK"},
  {"ac_no":148,"constituency":"Kunnam","district":"Perambalur","mla":"Sivasankar S.S.","party":"DMK"},
  {"ac_no":149,"constituency":"Ariyalur","district":"Ariyalur","mla":"Rajendran S.","party":"AIADMK"},
  {"ac_no":150,"constituency":"Jayankondam","district":"Ariyalur","mla":"Vaithilingam G.","party":"PMK"},
  {"ac_no":151,"constituency":"Tittakudi (SC)","district":"Cuddalore","mla":"Ganesan C.V.","party":"DMK"},
  {"ac_no":152,"constituency":"Vriddhachalam","district":"Cuddalore","mla":"Premalatha Vijayakant","party":"DMDK"},
  {"ac_no":153,"constituency":"Neyveli","district":"Cuddalore","mla":"Rajendran R.","party":"AIADMK"},
  {"ac_no":154,"constituency":"Panruti","district":"Cuddalore","mla":"Mohan K.","party":"AIADMK"},
  {"ac_no":155,"constituency":"Cuddalore","district":"Cuddalore","mla":"B. Rajkumar","party":"TVK"},
  {"ac_no":156,"constituency":"Kurinjipadi","district":"Cuddalore","mla":"M.R.K. Panneerselvam","party":"DMK"},
  {"ac_no":157,"constituency":"Bhuvanagiri","district":"Cuddalore","mla":"Arunmozhithevan A.","party":"AIADMK"},
  {"ac_no":158,"constituency":"Chidambaram","district":"Cuddalore","mla":"Thamimun Ansari M.","party":"DMK"},
  {"ac_no":159,"constituency":"Kattumannarkoil (SC)","district":"Cuddalore","mla":"L.E. Jothimani","party":"VCK"},
  {"ac_no":160,"constituency":"Sirkazhi (SC)","district":"Mayiladuthurai","mla":"Senthilselvan R.","party":"DMK"},
  {"ac_no":161,"constituency":"Mayiladuthurai","district":"Mayiladuthurai","mla":"Jamal Mohamed Younoos Y.N.","party":"INC"},
  {"ac_no":162,"constituency":"Poompuhar","district":"Mayiladuthurai","mla":"Nivedha M. Murugan","party":"DMK"},
  {"ac_no":163,"constituency":"Nagapattinam","district":"Nagapattinam","mla":"M.H. Jawahirullah","party":"DMK"},
  {"ac_no":164,"constituency":"Kilvelur (SC)","district":"Nagapattinam","mla":"Latha T.","party":"CPI(M)"},
  {"ac_no":165,"constituency":"Vedaranyam","district":"Nagapattinam","mla":"Manian O.S.","party":"AIADMK"},
  {"ac_no":166,"constituency":"Thiruthuraipoondi (SC)","district":"Thiruvarur","mla":"Marimuthu K.","party":"CPI"},
  {"ac_no":167,"constituency":"Mannargudi","district":"Thiruvarur","mla":"Kamaraj S.","party":"AMMK"},
  {"ac_no":168,"constituency":"Thiruvarur","district":"Thiruvarur","mla":"Kalaivanan Poondi K.","party":"DMK"},
  {"ac_no":169,"constituency":"Nannilam","district":"Thiruvarur","mla":"Kamaraj R.","party":"AIADMK"},
  {"ac_no":170,"constituency":"Thiruvidaimarudur (SC)","district":"Thanjavur","mla":"Govi. Chezhiyan","party":"DMK"},
  {"ac_no":171,"constituency":"Kumbakonam","district":"Thanjavur","mla":"Vinoth","party":"TVK"},
  {"ac_no":172,"constituency":"Papanasam","district":"Thanjavur","mla":"A.M. Shahjahan","party":"IUML"},
  {"ac_no":173,"constituency":"Thiruvaiyaru","district":"Thanjavur","mla":"Durai Chandrasekaran","party":"DMK"},
  {"ac_no":174,"constituency":"Thanjavur","district":"Thanjavur","mla":"R. Vijaysaravanan","party":"TVK"},
  {"ac_no":175,"constituency":"Orathanadu","district":"Thanjavur","mla":"R. Vaithilingam","party":"DMK"},
  {"ac_no":176,"constituency":"Pattukkottai","district":"Thanjavur","mla":"Annadurai K.","party":"DMK"},
  {"ac_no":177,"constituency":"Peravurani","district":"Thanjavur","mla":"Ashokkumar N.","party":"DMK"},
  {"ac_no":178,"constituency":"Gandarvakkottai (SC)","district":"Pudukkottai","mla":"N. Subramanian","party":"TVK"},
  {"ac_no":179,"constituency":"Viralimalai","district":"Pudukkottai","mla":"Vijayabaskar C.","party":"AIADMK"},
  {"ac_no":180,"constituency":"Pudukkottai","district":"Pudukkottai","mla":"V. Muthuraja","party":"DMK"},
  {"ac_no":181,"constituency":"Thirumayam","district":"Pudukkottai","mla":"Regupathy S.","party":"DMK"},
  {"ac_no":182,"constituency":"Alangudi","district":"Pudukkottai","mla":"Siva V. Meyyanathan","party":"DMK"},
  {"ac_no":183,"constituency":"Aranthangi","district":"Pudukkottai","mla":"Mohamed Farvas J.","party":"TVK"},
  {"ac_no":184,"constituency":"Karaikudi","district":"Sivaganga","mla":"Dr. Prabhu T.K.","party":"TVK"},
  {"ac_no":185,"constituency":"Tiruppattur","district":"Sivaganga","mla":"Seenivasa Sethupathy R.","party":"TVK"},
  {"ac_no":186,"constituency":"Sivaganga","district":"Sivaganga","mla":"Kulanthai Rani A.","party":"TVK"},
  {"ac_no":187,"constituency":"Manamadurai (SC)","district":"Sivaganga","mla":"Elangovan D.","party":"TVK"},
  {"ac_no":188,"constituency":"Melur","district":"Madurai","mla":"P. Viswanathan","party":"INC"},
  {"ac_no":189,"constituency":"Madurai East","district":"Madurai","mla":"Karthikeyan S.","party":"TVK"},
  {"ac_no":190,"constituency":"Sholavandan (SC)","district":"Madurai","mla":"Karuppaiah M.V.","party":"TVK"},
  {"ac_no":191,"constituency":"Madurai North","district":"Madurai","mla":"A. Kallanai","party":"TVK"},
  {"ac_no":192,"constituency":"Madurai South","district":"Madurai","mla":"M.M. Gopison","party":"TVK"},
  {"ac_no":193,"constituency":"Madurai Central","district":"Madurai","mla":"Madhar Badhurudeen","party":"TVK"},
  {"ac_no":194,"constituency":"Madurai West","district":"Madurai","mla":"Thangapandi S.R.","party":"TVK"},
  {"ac_no":195,"constituency":"Thiruparankundram","district":"Madurai","mla":"Nirmalkumar R.","party":"TVK"},
  {"ac_no":196,"constituency":"Thirumangalam","district":"Madurai","mla":"Manimaran M.","party":"DMK"},
  {"ac_no":197,"constituency":"Usilampatti","district":"Madurai","mla":"Vijay M.","party":"TVK"},
  {"ac_no":198,"constituency":"Andipatti","district":"Theni","mla":"Maharajan A.","party":"DMK"},
  {"ac_no":199,"constituency":"Periyakulam (SC)","district":"Theni","mla":"Sabari Iyngaran G.","party":"TVK"},
  {"ac_no":200,"constituency":"Bodinayakanur","district":"Theni","mla":"Panneerselvam O.","party":"DMK"},
  {"ac_no":201,"constituency":"Cumbum","district":"Theni","mla":"Jeganathmishra PLA","party":"TVK"},
  {"ac_no":202,"constituency":"Rajapalayam","district":"Virudhunagar","mla":"Jegadeshwari K.","party":"TVK"},
  {"ac_no":203,"constituency":"Srivilliputhur (SC)","district":"Virudhunagar","mla":"Karthik A.","party":"TVK"},
  {"ac_no":204,"constituency":"Sattur","district":"Virudhunagar","mla":"Kadarkarairaj A.","party":"DMK"},
  {"ac_no":205,"constituency":"Sivakasi","district":"Virudhunagar","mla":"Keerthana S.","party":"TVK"},
  {"ac_no":206,"constituency":"Virudhunagar","district":"Virudhunagar","mla":"Selvam P.","party":"TVK"},
  {"ac_no":207,"constituency":"Aruppukkottai","district":"Virudhunagar","mla":"Ramachandran K.K.S.S.R.","party":"DMK"},
  {"ac_no":208,"constituency":"Tiruchuli","district":"Virudhunagar","mla":"Thangam Thenarasu","party":"DMK"},
  {"ac_no":209,"constituency":"Paramakudi (SC)","district":"Ramanathapuram","mla":"Adv. Kathiravan K.K.","party":"DMK"},
  {"ac_no":210,"constituency":"Tiruvadanai","district":"Ramanathapuram","mla":"Rajeev","party":"TVK"},
  {"ac_no":211,"constituency":"Ramanathapuram","district":"Ramanathapuram","mla":"Katharbatcha Muthuramalingam","party":"DMK"},
  {"ac_no":212,"constituency":"Mudhukulathur","district":"Ramanathapuram","mla":"R.S. Rajakannappan","party":"DMK"},
  {"ac_no":213,"constituency":"Vilathikulam","district":"Thoothukudi","mla":"Markandayan G.V.","party":"DMK"},
  {"ac_no":214,"constituency":"Thoothukkudi","district":"Thoothukudi","mla":"Srinath","party":"TVK"},
  {"ac_no":215,"constituency":"Tiruchendur","district":"Thoothukudi","mla":"Anitha R. Radhakrishnan","party":"DMK"},
  {"ac_no":216,"constituency":"Srivaikuntam","district":"Thoothukudi","mla":"Saravanan G.","party":"TVK"},
  {"ac_no":217,"constituency":"Ottapidaram (SC)","district":"Thoothukudi","mla":"P. Mathanraja","party":"TVK"},
  {"ac_no":218,"constituency":"Kovilpatti","district":"Thoothukudi","mla":"Karunanithi K.","party":"DMK"},
  {"ac_no":219,"constituency":"Sankarankovil (SC)","district":"Tenkasi","mla":"Dr. Dhilipan Jaishankar","party":"AIADMK"},
  {"ac_no":220,"constituency":"Vasudevanallur (SC)","district":"Tenkasi","mla":"E. Raja","party":"DMK"},
  {"ac_no":221,"constituency":"Kadayanallur","district":"Tenkasi","mla":"Rajendran T.M.","party":"DMK"},
  {"ac_no":222,"constituency":"Tenkasi","district":"Tenkasi","mla":"Dr. Kalai Kathiravan","party":"DMK"},
  {"ac_no":223,"constituency":"Alangulam","district":"Tenkasi","mla":"Paul Manoj Pandian","party":"DMK"},
  {"ac_no":224,"constituency":"Tirunelveli","district":"Tirunelveli","mla":"Murughan R.S.","party":"TVK"},
  {"ac_no":225,"constituency":"Ambasamudram","district":"Tirunelveli","mla":"Dr. Esakki Subaya","party":"AIADMK"},
  {"ac_no":226,"constituency":"Palayamkottai","district":"Tirunelveli","mla":"M. Abdul Wahab","party":"DMK"},
  {"ac_no":227,"constituency":"Nanguneri","district":"Tirunelveli","mla":"Reddiarpatti V. Narayanan","party":"TVK"},
  {"ac_no":228,"constituency":"Radhapuram","district":"Tirunelveli","mla":"Dr. Sathish Christopher","party":"TVK"},
  {"ac_no":229,"constituency":"Kanniyakumari","district":"Kanniyakumari","mla":"Thalavai Sundaram N.","party":"AIADMK"},
  {"ac_no":230,"constituency":"Nagercoil","district":"Kanniyakumari","mla":"Austin","party":"DMK"},
  {"ac_no":231,"constituency":"Colachal","district":"Kanniyakumari","mla":"Tharahai Cuthbert","party":"INC"},
  {"ac_no":232,"constituency":"Padmanabhapuram","district":"Kanniyakumari","mla":"Chellaswamy R.","party":"CPI(M)"},
  {"ac_no":233,"constituency":"Vilavancode","district":"Kanniyakumari","mla":"Praveen T.T.","party":"INC"},
  {"ac_no":234,"constituency":"Killiyoor","district":"Kanniyakumari","mla":"Rajesh Kumar S.","party":"INC"}
];

// Derived lookup maps for fast access
export const DISTRICTS_LIST = [...new Set(MLA_DATA.map(m => m.district))].sort();

export const getConstituenciesByDistrict = (district) =>
  MLA_DATA.filter(m => m.district === district).sort((a, b) => a.ac_no - b.ac_no);

export const getMlaByConstituency = (constituency) =>
  MLA_DATA.find(m => m.constituency === constituency) || null;

export const getOfficerByDistrict = (district) =>
  DISTRICT_OFFICERS[district] || `District Collector – ${district}`;
